apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: hml
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-http-redirect
  namespace: hml
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: hml-https-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  rules:
    - host: hml.129.213.121.122.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oficina
                port:
                  name: http
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: prod
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oficina-http-redirect
  namespace: prod
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: prod-https-redirect@kubernetescrd
    traefik.ingress.kubernetes.io/router.priority: "1"
spec:
  ingressClassName: traefik
  rules:
    - host: oficina.129.213.121.122.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oficina
                port:
                  name: http
